#!/usr/bin/env python
import sys,os,shutil,os.path
from struct_utils  import *
from constants     import *
from io_utils      import *
from data_utils    import * 
from bandstruct    import * 

def f_Help_Info():
  myname = sys.argv[0]
  print "\n"+myname + ": a Python script to extract the important information from GAP2 output\n"
  print "   Usage: " + os.path.basename(myname) + " [options]"\
  + """
  Options:
    -h                       # display this help information
    -m <mode>                 # var = Eg
    -o <outfile=case.outgw>  # give the name for the vasp OUTCAR file    
  Examples:
  """
  sys.exit(0)



  
