#!/usr/bin/env python

import sys,os,shutil
from siesta_utils import * 
from io_utils import *

# default input and output format 

def f_Help_Info():
  myname = sys.argv[0]
  print "\n"+myname + ": a Python script to plot band structures using SIESTA output sys_label.bands \n"
  print "   Usage: " + os.path.basename(myname) + " [options]"\
  + """
  Options:
    -h                # display this help information
    -f <file >        # prefix for input and output
    -o <out_format>   # format for output data = 'gnp' 
    -r <ebmin ebmax>  # range to be plotted 
    -z <shift>        # how to choose energy zero 'fermi' or 'vbm'
   
    --debug           # set debug mode
  Examples:
  """
  sys.exit(0)
  
def_range = ( -15.0, 15.0) 
def_ezero = 'vbm'
def_out = 'gnp'
def_file = os.path.basename(os.getcwd())

if f_Getopt('-h',0,False): f_Help_Info()

file  = f_Getopt('-f',1,def_file  ) 
range = f_Getopt('-r',2,def_range ) 
ezero = f_Getopt('-z',1,def_ezero ) 
out   = f_Getopt('-o',1,def_out   )

f_Plot_Bands(file,erange=range,out=out,ezero=ezero)

