#!/usr/bin/env python

import sys,os,shutil
from w2k_utils import *
from struct_utils import *

case_name = f_Check_Name()

latt_type,alatt,basis=f_Read_Struct()

print "Lattice Type:     ",latt_type
print "Lattice Constants:",alatt
print "Internal coordinates:"
for i in range(len(basis)): print basis[i]

# write lattice structure into the siesta format

# check the number of species 

latt_vec = f_Latt_Vectors(latt_type,alatt)

f_Write_Struct_aims(case_name,basis,latt_vec)

